[workspace]
members = [
    "packages/presets",
    "packages/security",
    "packages/token",
    "packages/upgrades",
    "packages/testing",
    "packages/test_common",
]

[package]
name = "openzeppelin"
version.workspace = true

[workspace.package]
version = "0.15.1"
edition = "2023_11"
cairo-version = "2.7.0"
scarb-version = "2.7.0"
authors = ["OpenZeppelin Community <maintainers@openzeppelin.org>"]
description = "OpenZeppelin Contracts written in Cairo for Starknet, a decentralized ZK Rollup"
documentation = "https://docs.openzeppelin.com/contracts-cairo"
readme = "README.md"
repository = "https://github.com/OpenZeppelin/cairo-contracts"
license-file = "LICENSE"
keywords = [
    "openzeppelin",
    "starknet",
    "cairo",
    "contracts",
    "security",
    "standards",
]

[workspace.dependencies]
starknet = "2.7.0"
snforge_std = "0.26.0"

[dependencies]
starknet.workspace = true
openzeppelin_access = "0.15.1"
openzeppelin_account = "0.15.1"
openzeppelin_governance = "0.15.1"
openzeppelin_presets = { path = "packages/presets" }
openzeppelin_security = { path = "packages/security" }
openzeppelin_token = { path = "packages/token" }
openzeppelin_upgrades = { path = "packages/upgrades" }

[dev-dependencies]
snforge_std.workspace = true
openzeppelin_test_common = { path = "packages/test_common" }
openzeppelin_testing = { path = "packages/testing" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[workspace.tool.fmt]
sort-module-level-items = true

[tool]
fmt.workspace = true
